networks:
  instagram-network:

services:
  backend:
    networks:
      - instagram-network

    build:
      context: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3  # монтируем в файл в контейнере
    ports: []
    depends_on:
      - cache
    environment:
      - DEBUG=1
      - REDIS_URL=redis://cache:6379

  frontend:
    networks:
      - instagram-network

    build:
      context: ./frontend
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports: []
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  cache:
    networks:
      - instagram-network

    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"


  nginx:
    networks:
      - instagram-network

    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  sqlite_db:
