networks:
  instagram-network:

services:

  backend:
    # In development

  frontend:
    networks:
    - instagram-network
    build:
      context: ./frontend
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  cache:
    networks:
    - instagram-network
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  sqlite_db: