services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
      - sqlite_db:/app  # монтируем в папку, не в файл
    ports:
      - "8000:8000"
    depends_on:
      - cache
    environment:
      - DEBUG=1
      - REDIS_URL=redis://cache:6379

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  cache:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  sqlite_db:
